### ISSUE TITLE
No new data since 2016-12-07

### ISSUE THREAD

**Issue by vincentsarago** [developmentseed/sentinel-api-data#5]
It seems there is something broken here ! 
There is no new sentinel-2 data in the database since December 7th. 

Thanks

cc @matthewhanson @scisco @drewbo

**Comment by drewbo** [comment]
Thanks @vincentsarago, I've been working on a fix for the new metadata format and will deploy soon

**Comment by vincentsarago** [comment]
Thanks @drewbo

**Comment by drewbo** [comment]
Should be getting new data in now (will take a little while to get everything added) and I'll close this ticket once we merge back the relevant code (it's just a dependency update)

**Comment by drewbo** [comment]
Closed via #6
